version: '3.4'

services:

  l2:
    image: j2io/jfc-op-geth:v2.1
    restart: always
    ports:
      - "8545:8545"
    volumes:
      - "./l2_data:/db"
      - "./genesis-l2.json:/genesis.json"
      - "./jwt.txt:/config/test-jwt-secret.txt"
      - "./entrypoint.sh:/entrypoint.sh"
    entrypoint:  # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"

  op-node:
    depends_on:
      - l2
    image: j2io/jfc-op-node:2.3-bsc
    command: >
      op-node
      --l1.trustrpc
      --l1.rpckind=erigon
      --l1=https://rpc.jfinchain.com
      --l2=http://l2:8551
      --l2.jwt-secret=/config/jwt.txt
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
      --p2p.bootnodes=enr:-J64QFuOWBOp8BClQF4CAnD6dbmxCgsAtkcY876LQxgyFtdXC9bqTF0CLveypCLKxDHlTGvgVOQunSgOHik3lyc5-iCGAYbLZMVLgmlkgnY0gmlwhEFsaNSHb3BzdGFja4SVrxUAiXNlY3AyNTZrMaECCSurYjeZwx9vc0iOgtXsKxvqjhed9xBiaPrJKCxHJViDdGNwgiMrg3VkcIIjKw
      --verifier.l1-confs=0
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9222
      --p2p.listen.udp=9222
      --p2p.nat=true
      --p2p.priv.path=/config/node.txt
    ports:
      - "9222:9222"
    restart: always
    volumes:
      - "./jwt.txt:/config/jwt.txt"
      - "./node.txt:/config/node.txt"
      - "./rollup.json:/rollup.json"

