version: '3.4'


services:

  l2:
    image: j2io/op-geth:beta
    ports:
      - "9545:8545"
      - "9546:8546"
    volumes:
      - "./l2_data:/db"
      - "./genesis.json:/genesis.json"
      - "./jwt-secret.txt:/config/jwt-secret.txt"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/jwt-secret.txt"

  op-node:
    depends_on:
      - l2
    image: j2io/op-node:beta
    command: >
      op-node
      --l1=http://65.108.14.187:8545
      --l2=http://l2:8551
      --l2.jwt-secret=/config/jwt-secret.txt
      --sequencer.enabled
      --sequencer.l1-confs=0
      --verifier.l1-confs=0
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9003
      --p2p.listen.udp=9003
      --snapshotlog.file=/op_log/snapshot.log
      --p2p.priv.path=/config/p2p-node-key.txt
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --pprof.enabled
    volumes:
      - ./p2p-node-key.txt:/config/p2p-node-key.txt
      - ./jwt-secret.txt:/config/jwt-secret.txt
      - ./rollup.json:/rollup.json
      - ./op_log:/op_log

