version: '3.4'

services:

  l2:
    image: j2io/jfc-op-geth:v2.1
    ports:
      - "8545:8545"
    volumes:
      - "./l2_data:/db"
      - "./genesis-l2.json:/genesis.json"
      - "./jwt.txt:/config/test-jwt-secret.txt"
      - "./entrypoint.sh:/entrypoint.sh"
    entrypoint:  # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
      - "--authrpc.jwtsecret=/config/test-jwt-secret.txt"

  op-node:
    depends_on:
      - l2
    image: j2io/jfc-op-node:v2.1
    command: >
      op-node
      --l1.trustrpc
      --l1=https://rpc.jfinchain.com
      --l2=http://l2:8551
      --l2.jwt-secret=/config/test-jwt-secret.txt
      --rollup.config=/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8545
    volumes:
      - "./jwt.txt:/config/test-jwt-secret.txt"
      - "./rollup.json:/rollup.json"
    environment:
      - OP_NODE_LOG_LEVEL=info
      - OP_NODE_METRICS_ADDR=0.0.0.0
      - OP_NODE_METRICS_ENABLED=true
      - OP_NODE_METRICS_PORT=7300
      - OP_NODE_P2P_BOOTNODES=enr:-J64QMO9A5odoDGJi178_z2SMjOLU50NWOKk40dEyNAmVAXaH2hpDCVpYT2mJWHT8tjxpPdkAa_eKrR2oKvK0N0AGRyGAYbMIt3HgmlkgnY0gmlwhEFtGgeHb3BzdGFja4SVrxUAiXNlY3AyNTZrMaEC6El-hPZuJJurOtDhjAQaUdUdcvcRmO4JLZV23BN2JOaDdGNwgibNg3VkcIImzQ
